### ISSUE TITLE
AttributeError: module 'ida_bytes' has no attribute 'compiled_binpat_vec_t'

### ISSUE THREAD

**Issue by mucomplex** [MlsDmitry/better-rtti-parser#2]
I got this error on IDA pro 7.5

C:\Users\Commando10\Desktop\better-rtti-parser-master\better-rtti-parser-master\rtti_parse.py: module 'ida_bytes' has no attribute 'compiled_binpat_vec_t'
Traceback (most recent call last):
  File "C:\Users\Commando10\Desktop\IDA_PRO\IDA Pro 7.5\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/Commando10/Desktop/better-rtti-parser-master/better-rtti-parser-master/rtti_parse.py", line 136, in <module>
    main()
  File "C:/Users/Commando10/Desktop/better-rtti-parser-master/better-rtti-parser-master/rtti_parse.py", line 131, in main
    process()
  File "C:/Users/Commando10/Desktop/better-rtti-parser-master/better-rtti-parser-master/rtti_parse.py", line 94, in process
    addr_ea = search(symbol_name)
  File "C:/Users/Commando10/Desktop/better-rtti-parser-master/better-rtti-parser-master\core\common.py", line 85, in search
    pattern_obj = ida_bytes.compiled_binpat_vec_t()
AttributeError: module 'ida_bytes' has no attribute 'compiled_binpat_vec_t'

**Comment by MlsDmitry** [comment]
Could you open C:\Users\Commando10\Desktop\IDA_PRO\IDA Pro 7.5\python\3\ida_bytes.py and check if compiled_binpat_vec_t is there ?

**Comment by delvinru** [comment]
There is a similar problem, there is no `compiled_binpat_vec_t` function in the `ida_bytes.py`.
```
C:\...\better-rtti-parser\rtti_parse.py: module 'ida_bytes' has no attribute 'compiled_binpat_vec_t'
Traceback (most recent call last):
  File "C:\...\IDA 7.5\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/.../better-rtti-parser/rtti_parse.py", line 136, in <module>
    main()
  File "C:/.../better-rtti-parser/rtti_parse.py", line 131, in main
    process()
  File "C:/.../better-rtti-parser/rtti_parse.py", line 94, in process
    addr_ea = search(symbol_name)
  File "C:/.../better-rtti-parser\core\common.py", line 85, in search
    pattern_obj = ida_bytes.compiled_binpat_vec_t()
AttributeError: module 'ida_bytes' has no attribute 'compiled_binpat_vec_t'
```

**Comment by MlsDmitry** [comment]
Okay, thanks, I'll research this issue. Could you also check if `compiled_binpat_vect_t` exists in `ida_bytes.py`
